/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class Agency_Address (
  /* Agency's street address */
  address1: Option[String],
  /* Agency's extended address which could include apt */
  address2: Option[String],
  /* Agency's city of business */
  city: Option[String],
  /* Agency's state of business */
  state: Option[String],
  /* Agency's Zipcode/PostalCode */
  zipCode: Option[String]
) extends ApiModel


