/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class Agency (
  /* Unique ID assigned to each Implementing Agency */
  siteID: String,
  /* Name of Implementing Agency */
  aGENCYINFO0NAME: String,
  /* Name of Implementing Agency */
  siteName: String,
  address: Option[Agency_Address],
  /* Agency's Phone number */
  phone1: Double,
  /* Type of Organization */
  aGENCYINFO1TYPE: AgencyEnums.AGENCYINFO1TYPE,
  /* Low-income criteria used for eligibility */
  aGENCYINFO1LOWINCOMECRITERA: String,
  /* Low-income criteria used for eligibility */
  aGENCYINFO1LOWINCOMEPERCENT: String,
  /* Low-income criteria used for eligibility */
  aGENCYINFO1LOWINCOMEDESCRIPTION: String,
  /* Implementing Agency Website */
  aGENCYINFO1WEBSITE: Option[String],
  /* Service level Implementing Agency Covers */
  sERVICELEVELCOVERED: Option[AgencyEnums.SERVICELEVELCOVERED],
  cOUNTIESSERVED: Option[String],
  /* Date Implementing Agency began implementing NFP */
  aGENCYINFO1INITIATIONDATE: String,
  /* Date of the first home visit at that Implementing Agency */
  aGENCYDATEFIRSTHOMEVISIT: String
) extends ApiModel

object AgencyEnums {

  type AGENCYINFO1TYPE = AGENCYINFO1TYPE.Value
  type SERVICELEVELCOVERED = SERVICELEVELCOVERED.Value
  object AGENCYINFO1TYPE extends Enumeration {
    val `Public Health` = Value("Public Health")
    val `Agency or Clinic` = Value("Agency or Clinic")
    val Hospital = Value("Hospital")
    val `Community Based Organization` = Value("Community Based Organization")
  }

  object SERVICELEVELCOVERED extends Enumeration {
    val City = Value("City")
    val County = Value("County")
    val Parish = Value("Parish")
    val Region = Value("Region")
    val Tribe = Value("Tribe")
  }

}

