/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class Client (
  /* What type of record New or Update */
  typeOfRecord: ClientEnums.TypeOfRecord,
  /* Unique NPF Client Identifier - pseudonym = CL_EN_GEN_ID */
  clientSourceSystemID: String,
  /* The unique identifier from the source system - pseudonym = CLIENT_0_ID_AGENCY */
  agencySourceSystemID: String,
  /* Client's First Name */
  firstName: String,
  /* Client's Last Name */
  lastName: String,
  /* Client's Date of Birth */
  clientDOB: Option[String],
  /* Client's Social Security Number */
  clientSSN: Option[Int],
  address: Option[Client_Address],
  /* Client's Address */
  email: Option[String],
  /* Client's Home Phone Number */
  homePhone: Option[Double],
  /* Client's Work Phone Number */
  workPhone: Option[Double],
  /* Client's Cell Phone Number - pseudonym = REFERRAL_PROSPECT_DEMO_1_CELL */
  cellPhone: Option[Double],
  /* Client's estimated due date  - pseudonym = REFERRAL_PROSPECT_DEMO_1_EDD */
  clientEDD: Option[String],
  /* Client's primary language - pseudonym = DEMO_CLIENT_INTAKE_0_LANGUAGE */
  primaryLanguage: Option[String],
  /* Client's Ethnicity - pseudonym = DEMO_CLIENT_INTAKE_0_ETHNICITY */
  ethnicity: Option[ClientEnums.Ethnicity],
  /* Client's race, can be more than one - pseudonym = DEMO_CLIENT_INTAKE_0_RACE */
  race: Option[Seq[Null]]
) extends ApiModel

object ClientEnums {

  type TypeOfRecord = TypeOfRecord.Value
  type Ethnicity = Ethnicity.Value
  object TypeOfRecord extends Enumeration {
    val `NEW` = Value("NEW")
    val UPDATE = Value("UPDATE")
  }

  object Ethnicity extends Enumeration {
    val `Hispanic or Latina` = Value("Hispanic or Latina")
    val `Not Hispanic or Latina` = Value("Not Hispanic or Latina")
    val `Declined to self-identify` = Value("Declined to self-identify")
  }

}

