/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class Nurse_Address (
  addressLine1: Option[String],
  addressLine2: Option[String],
  addressLine3: Option[String],
  city: Option[String],
  state: Option[String],
  zip: Option[String],
  country: Option[String]
) extends ApiModel


