/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class Nurse (
  /* What type of record New or Update */
  typeOfRecord: NurseEnums.TypeOfRecord,
  /* The unique identifier from the source system */
  sourceSystemID: String,
  /* The unique identifier from the source system */
  agencySourceSystemID: String,
  firstName: String,
  middleName: Option[String],
  lastName: String,
  dateStarted: String,
  dateEnded: Option[String],
  address: Option[Nurse_Address]
) extends ApiModel

object NurseEnums {

  type TypeOfRecord = TypeOfRecord.Value
  object TypeOfRecord extends Enumeration {
    val `NEW` = Value("NEW")
    val UPDATE = Value("UPDATE")
  }

}

